### ISSUE TITLE
docker ContextualVersionConflict

### ISSUE THREAD

**Issue by akshay0808** [aws-cloudformation/cloudformation-cli-python-plugin#147]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/init.py", line 168, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2315, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2338, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docker 4.2.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('docker>=4.3.1'), {'cloudformation-cli'})
```

**Comment by ammokhov** [comment]
could you provide more details?

**Comment by PatMyron** [comment]
related to https://github.com/aws-cloudformation/cloudformation-cli/blob/b01caaea2a76416c4f2108efd4f165536b9d52a0/setup.py#L52
