### ISSUE TITLE
OOTB generated python CF resource cannot be used with cfn test 

### ISSUE THREAD

**Issue by carpnick** [aws-cloudformation/cloudformation-cli-python-plugin#247]
Repro:

- Install latest cloudformation-cli
- Install master branch of this repo
- Generate a new resource type - in my example I used python3.9
- run `cfn submit --dry-run`
- run sam build
- in new terminal run `sam local start-lambda`
- run just one contract test -`cfn test -- -k contract_create_delete`
- Error from cryptography library:
- `Unable to import module 'dd_dd_test1.handlers': cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location)`

Still investigating root cause.

**Comment by carpnick** [comment]
Full trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/task/dd_dd_test1/handlers.py", line 3, in <module>
    from cloudformation_cli_python_lib import (
  File "/var/task/cloudformation_cli_python_lib/__init__.py", line 4, in <module>
    from .hook import Hook  # noqa: F401
  File "/var/task/cloudformation_cli_python_lib/hook.py", line 9, in <module>
    from .cipher import Cipher, KmsCipher
  File "/var/task/cloudformation_cli_python_lib/cipher.py", line 4, in <module>
    import aws_encryption_sdk  # type: ignore
  File "/var/task/aws_encryption_sdk/__init__.py", line 19, in <module>
    from aws_encryption_sdk.caches.local import LocalCryptoMaterialsCache  # noqa
  File "/var/task/aws_encryption_sdk/caches/__init__.py", line 25, in <module>
    from ..internal.formatting.encryption_context import serialize_encryption_context
  File "/var/task/aws_encryption_sdk/internal/formatting/__init__.py", line 14, in <module>
    from .serialize import serialize_header
  File "/var/task/aws_encryption_sdk/internal/formatting/serialize.py", line 17, in <module>
    import aws_encryption_sdk.internal.defaults
  File "/var/task/aws_encryption_sdk/internal/defaults.py", line 16, in <module>
    import aws_encryption_sdk.identifiers
  File "/var/task/aws_encryption_sdk/identifiers.py", line 18, in <module>
    from cryptography.hazmat.primitives.asymmetric import ec, padding, rsa
  File "/var/task/cryptography/hazmat/primitives/asymmetric/ec.py", line 10, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/var/task/cryptography/hazmat/_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location)

```

**Comment by carpnick** [comment]
Note - when using `pydeps` it sees the dependency but not with `pipdeptree`.  Not sure how PIP is figuring out to grab it.

Relevant Dep Graphs (pydeps):
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/6966179/212975688-45ecc96b-23e1-43f4-81f0-39e5ea7ad336.png">

pipdeptree:
```
cloudformation-cli-python-plugin==2.1.7
  - cloudformation-cli [required: >=0.2.26, installed: 0.2.28]
    - boto3 [required: >=1.10.20, installed: 1.26.50]
      - botocore [required: >=1.29.50,<1.30.0, installed: 1.29.50]
        - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
        - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.14]
      - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
      - s3transfer [required: >=0.6.0,<0.7.0, installed: 0.6.0]
        - botocore [required: >=1.12.36,<2.0a.0, installed: 1.29.50]
          - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
          - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
            - six [required: >=1.5, installed: 1.16.0]
          - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.14]
    - cfn-flip [required: >=1.2.3, installed: 1.3.0]
      - Click [required: Any, installed: 8.1.3]
      - PyYAML [required: >=4.1, installed: 5.4.1]
      - six [required: Any, installed: 1.16.0]
    - cfn-lint [required: >=0.43.0, installed: 0.72.8]
      - aws-sam-translator [required: >=1.56.0, installed: 1.57.0]
        - boto3 [required: >=1.19.5,==1.*, installed: 1.26.50]
          - botocore [required: >=1.29.50,<1.30.0, installed: 1.29.50]
            - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
            - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
              - six [required: >=1.5, installed: 1.16.0]
            - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.14]
          - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
          - s3transfer [required: >=0.6.0,<0.7.0, installed: 0.6.0]
            - botocore [required: >=1.12.36,<2.0a.0, installed: 1.29.50]
              - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
              - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
                - six [required: >=1.5, installed: 1.16.0]
              - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.14]
        - jsonschema [required: >=3.2,<5, installed: 3.2.0]
          - attrs [required: >=17.4.0, installed: 22.2.0]
          - pyrsistent [required: >=0.14.0, installed: 0.19.3]
          - setuptools [required: Any, installed: 65.6.3]
          - six [required: >=1.11.0, installed: 1.16.0]
        - pydantic [required: ~=1.10.2, installed: 1.10.4]
          - typing-extensions [required: >=4.2.0, installed: 4.4.0]
        - typing-extensions [required: ~=4.4.0, installed: 4.4.0]
      - jschema-to-python [required: ~=1.2.3, installed: 1.2.3]
        - attrs [required: Any, installed: 22.2.0]
        - jsonpickle [required: Any, installed: 3.0.1]
        - pbr [required: Any, installed: 5.11.1]
      - jsonpatch [required: Any, installed: 1.32]
        - jsonpointer [required: >=1.9, installed: 2.3]
      - jsonschema [required: >=3.0,<5, installed: 3.2.0]
        - attrs [required: >=17.4.0, installed: 22.2.0]
        - pyrsistent [required: >=0.14.0, installed: 0.19.3]
        - setuptools [required: Any, installed: 65.6.3]
        - six [required: >=1.11.0, installed: 1.16.0]
      - junit-xml [required: ~=1.9, installed: 1.9]
        - six [required: Any, installed: 1.16.0]
      - networkx [required: ~=2.4, installed: 2.8.8]
      - pyyaml [required: >5.4, installed: 5.4.1]
      - sarif-om [required: ~=1.0.4, installed: 1.0.4]
        - attrs [required: Any, installed: 22.2.0]
        - pbr [required: Any, installed: 5.11.1]
    - colorama [required: >=0.4.1, installed: 0.4.6]
    - docker [required: >=4.3.1, installed: 6.0.1]
      - packaging [required: >=14.0, installed: 23.0]
      - requests [required: >=2.26.0, installed: 2.28.2]
        - certifi [required: >=2017.4.17, installed: 2022.12.7]
        - charset-normalizer [required: >=2,<4, installed: 3.0.1]
        - idna [required: >=2.5,<4, installed: 3.4]
        - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.14]
      - urllib3 [required: >=1.26.0, installed: 1.26.14]
      - websocket-client [required: >=0.32.0, installed: 1.4.2]
    - hypothesis [required: >=4.32, installed: 6.62.1]
      - attrs [required: >=19.2.0, installed: 22.2.0]
      - exceptiongroup [required: >=1.0.0, installed: 1.1.0]
      - sortedcontainers [required: >=2.1.0,<3.0.0, installed: 2.4.0]
    - Jinja2 [required: >=2.11.3, installed: 3.1.2]
      - MarkupSafe [required: >=2.0, installed: 2.1.1]
    - jsonschema [required: >=3.0.1,<4.0, installed: 3.2.0]
      - attrs [required: >=17.4.0, installed: 22.2.0]
      - pyrsistent [required: >=0.14.0, installed: 0.19.3]
      - setuptools [required: Any, installed: 65.6.3]
      - six [required: >=1.11.0, installed: 1.16.0]
    - markupsafe [required: >=2.0.1, installed: 2.1.1]
    - nested-lookup [required: Any, installed: 0.2.25]
      - six [required: Any, installed: 1.16.0]
    - ordered-set [required: >=4.0.2, installed: 4.1.0]
    - pytest [required: >=4.5.0, installed: 7.2.1]
      - attrs [required: >=19.2.0, installed: 22.2.0]
      - exceptiongroup [required: >=1.0.0rc8, installed: 1.1.0]
      - iniconfig [required: Any, installed: 2.0.0]
      - packaging [required: Any, installed: 23.0]
      - pluggy [required: >=0.12,<2.0, installed: 1.0.0]
      - tomli [required: >=1.0.0, installed: 2.0.1]
    - pytest-localserver [required: >=0.5.0, installed: 0.7.0]
      - werkzeug [required: >=0.10, installed: 2.2.2]
        - MarkupSafe [required: >=2.1.1, installed: 2.1.1]
    - pytest-random-order [required: >=1.0.4, installed: 1.1.0]
      - pytest [required: >=3.0.0, installed: 7.2.1]
        - attrs [required: >=19.2.0, installed: 22.2.0]
        - exceptiongroup [required: >=1.0.0rc8, installed: 1.1.0]
        - iniconfig [required: Any, installed: 2.0.0]
        - packaging [required: Any, installed: 23.0]
        - pluggy [required: >=0.12,<2.0, installed: 1.0.0]
        - tomli [required: >=1.0.0, installed: 2.0.1]
    - PyYAML [required: >=5.1,<6.0, installed: 5.4.1]
    - requests [required: >=2.22, installed: 2.28.2]
      - certifi [required: >=2017.4.17, installed: 2022.12.7]
      - charset-normalizer [required: >=2,<4, installed: 3.0.1]
      - idna [required: >=2.5,<4, installed: 3.4]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.14]
    - Werkzeug [required: >=0.15, installed: 2.2.2]
      - MarkupSafe [required: >=2.1.1, installed: 2.1.1]
  - types-dataclasses [required: >=0.1.5, installed: 0.6.6]
pip==22.3.1

```

**Comment by carpnick** [comment]
Workaround:
Change generated requirements to this:
```
cloudformation-cli-python-lib>=2.1.9
cryptography==3.4.8
```

**Comment by carpnick** [comment]
Found out issue:

1st issue:
Template assumes X86.  If you are on an Apple Mac M1, you have to modify the SAM template to use arm64 using the `Architectures` property.   User error. 

Enhancement Request -  With `cfn init` ask user architecture and support arm64 and x86/AMD64 and modify templating of new resources as required.

2nd issue:
Fundamentally we have a broken workflow I think.  Any python package that requires native install cannot support the `copysource` workflow that SAM supports.  Instead it must use the dependency resolver workflow where dependencies are installed as part of `sam build`.  This will not work in this case because the `requirements.txt` needs to be in the root of the repo and in the `src` folder at the same time.  Even if we solve that part with automation, we are testing significantly different locally compared to what Lambda will run.  Lambda/CF Extensions are expecting the [ZIP file](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourceversion.html#cfn-cloudformation-resourceversion-schemahandlerpackage).  That means while we may make this work locally with integration testing, it breaks down once we upload it to the real environment.

I have not gotten to E2E testing within Cloudformation yet.  But it seems this is a blocker.

AWS team - is there any plans to make it so we can ship native docker container images as an integration instead?  If not, how will we overcome the native dependency install?  In this case we cannot say `not supported` since `cryptography` is in the `cloudformation-cli-python-plugin` dependency tree, let alone customers having their own dependencies.

**Comment by carpnick** [comment]
More digging on 2nd issue:

Broken because of [this line](https://github.com/aws/aws-lambda-builders/blob/75927e35f7b91c5ca93d1800a406ac0d54e7dbac/aws_lambda_builders/workflows/python_pip/workflow.py#L33) more than likely.

Looks like SAM may have a work around.  Still digging.

**Comment by carpnick** [comment]
Complete hack workaround:

- run `cfn submit --dry-run`
- Modify template to use MetaData for make file
  -  ```
      Metadata:
      BuildMethod: makefile
      ```
- Create a makefile like the following in root repo:
```
build-TypeFunction:
	cp -R ./ $(ARTIFACTS_DIR)
```
- Run cmd from root of repo: `cp makefile build/makefile`
- Run `sam build`
- If done correctly, takes all `build` folder output and puts into the `.aws-sam/build` output.  Now when you run `sam local invoke TypeFunction` the code doesnt fail on the import.

This hack is to get around this line from aws lambda builders:
https://github.com/aws/aws-lambda-builders/blob/75927e35f7b91c5ca93d1800a406ac0d54e7dbac/aws_lambda_builders/workflows/python_pip/workflow.py#L33
