### ISSUE TITLE
Cloudformation fails with `Internal Failure` and no CloudWatch Logs

### ISSUE THREAD

**Issue by OElesin** [aws-cloudformation/cloudformation-cli-python-plugin#99]
For some reason, after successfully submitting to CFN registry via the CLI with the command: `cfn submit`, and successfully testing with `sam local invoke TestEntrypoint --event test.json` - which launches the required resources in my AWS Account, creating the resource via the Cloudformation fails with the error `Internal Failure`.

I tried to find related CloudWatch logs, but nothing is available? Any ideas I might be missing anything?

**Comment by benkehoe** [comment]
We got this and it turned out that our schema was invalid in a way that the registry wasn't checking for but that failed deeper down in the service. I believe for us, it was that one of the properties used as `primaryIdentifier` had a value that was a list. Unfortunately, only the service team can actually find out, as these internal failures swallow the logs, which is a terrible customer experience.

**Comment by rjlohan** [comment]
Agree this isn't great. FWIW, `InternalFailure` is really just a mask exception for something we haven't handled specifically. If there are no CloudWatch logs then it's unlikely your type is even being invoked. Schema errors are the most likely culprit, but I'd have to look at a stack ARN to know for sure. If you have a support setup file an issue through that channel first.

**Comment by OElesin** [comment]
@rjlohan, thanks. Below is the schema:
```json
{
    "typeName": "CD4AutoML::Workflow::Deploy",
    "description": "Cd4AutoML managed end-to-end workflow with model serving REST API",
    "properties": {
        "S3TrainingDataPath": {
            "description": "S3 Path containing training data. Data format must CSV with headers.",
            "type": "string"
        },
        "TargetColumnName": {
            "description": "The name of the target column to be predicted. This MUST be last column in the CSV data in S3",
            "type": "string"
        },
        "NotificationEmail": {
            "description": "Valid email address to receive email notifications.",
            "type": "string",
            "pattern": "^[\\x20-\\x45]?[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$",
            "examples": [
                "test@example.com"
            ]
        },
        "WorkflowName": {
            "description": "Unique Name or Identifier for CD4AutoML workflow",
            "type": "string",
            "maxLength": 15
        },
        "Schedule": {
            "description": "Number of days before retraining AutoML model.",
            "type": "string"
        },
        "InferenceApi": {
            "description": "REST API URI for real time model inference available once workflow is completed",
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": [
        "S3TrainingDataPath",
        "TargetColumnName",
        "NotificationEmail",
        "WorkflowName"
    ],
    "readOnlyProperties": [
        "/properties/InferenceApi"
    ],
    "primaryIdentifier": [
        "/properties/WorkflowName"
    ],
    "handlers": {
        "create": {
            "permissions": [""]
        },
        "read": {
            "permissions": [""]
        },
        "update": {
            "permissions": [""]
        },
        "delete": {
            "permissions": [""]
        },
        "list": {
            "permissions": [""]
        }
    }
}
```

What may I be missing?

**Comment by rjlohan** [comment]
Nothing jumps out at me, but that RegEx on`NotificationEmail` is pretty gnarly. (I had an issue myself because of a malformed RegEx validation). See if it works without that one property present. Make sure you use the `--set-default` argument on `cfn submit` when publishing new versions.

If it's not that, we'd need a Stack ARN to dig deeper, but don't post those publicly.

**Comment by OElesin** [comment]
@rjlohan, I removed the Regex and it seems to work now. However, I get the error: `Resource timed out waiting for creation of physical resource`.

**Comment by rjlohan** [comment]
Great! Suggest you cut an issue to the main https://github.com/aws-cloudformation/cloudformation-cli repo showing that regex is a problem. We'll have to fix the validation.

For the new issue, you should be able to see logs now? This error occurs if your type does not return a primaryIdentifier value back to CloudFormation within 1 minute. The way to fix this is to return a `ProgressEvent.progress` with your `ResourceModel` populated with it's primaryIdentifier as soon as you have it, and then continue stabilization.

**Comment by OElesin** [comment]
This is my CREATE handler:
```python
@resource.handler(Action.CREATE)
def create_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
    )
    try:
        req_payload = {
            'S3TrainingDataPath': model.S3TrainingDataPath,
            'TargetColumnName': model.TargetColumnName,
            'NotificationEmail': model.NotificationEmail,
            'WorkflowName': model.WorkflowName,
        }
        # auth = HTTPBasicAuth('API_KEY', '')
        LOG.info(f"Creating workflow ${model.WorkflowName}")
        req = http.request(
            'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
        )
        payload = json.loads(req.data)
        deploy_status = payload['DeployStatus']
        while deploy_status == 'IN_PROGRESS':
            progress.status = OperationStatus.IN_PROGRESS
            req_payload['DeployId'] = payload['DeployId']
            req = http.request(
                'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
            )
            payload = json.loads(req.data)
            deploy_status = payload['DeployStatus']
            sleep(30)
        if deploy_status in ('FAILED', 'FAULT', 'STOPPED', 'TIMED_OUT'):
            LOG.error(f"Workflow ${model.WorkflowName} creation failed with status ${deploy_status}")
            raise exceptions.GeneralServiceException(f"creation failed with status ${deploy_status}")
        else:
            # Setting Status to success will signal to cfn that the operation is complete
            model.InferenceApi = payload.get('ApiUri', 'MyTestUrl')
            LOG.info(f"Created workflow ${model.WorkflowName} successfully")
            progress.status = OperationStatus.SUCCESS
    except TypeError as e:
        # exceptions module lets CloudFormation know the type of failure that occurred
        LOG.error(f"Workflow creation failed with status ${e}")
        raise exceptions.InternalFailure(f"was not expecting type {e}")
        # this can also be done by returning a failed progress event
        # return ProgressEvent.failed(HandlerErrorCode.InvalidRequest, f"was not expecting type {e}")
    return ProgressEvent(status=OperationStatus.SUCCESS, resourceModel=model, message="Workflow created")
```

**Comment by rjlohan** [comment]
I suspect the `sleep(30)` is probably the issue here. @jaymccon @jotompki can you explain how to progress through here correctly?

**Comment by jotompki** [comment]
I'd recommend removing the looping logic and instead conditionally return 
```
ProgressEvent(status=OperationStatus.IN_PROGRESS, resourceModel=model, message="Workflow creating")
```

or 

```
ProgressEvent(status=OperationStatus.SUCCESS, resourceModel=model, message="Workflow created")
```

depending on the response from the API. You can set the deployment id in  the callback context and that will be included in the next invocation request after the initial creation. You can then add some branching logic to execute your logic in the while loop if that is set in the callback context or simply try to create if it is not (the first invocation).

Our framework will handle reinvoking your resource handler. No need to try to stabilize on your own.

**Comment by OElesin** [comment]
Just did that after reading through the `ProgressEvent` again

Thanks for the response all

**Comment by richardhboyd** [comment]
I think this will work for you



```python
@resource.handler(Action.CREATE)
def create_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
        callbackContext=callback_context if callback_context is not None else {}
    )
    try:    
        req_payload = {
            'S3TrainingDataPath': model.S3TrainingDataPath,
            'TargetColumnName': model.TargetColumnName,
            'NotificationEmail': model.NotificationEmail,
            'WorkflowName': model.WorkflowName,
        }
        # auth = HTTPBasicAuth('API_KEY', '')
        LOG.info(f"Creating workflow ${model.WorkflowName}")
        # resuming from a long CREATE operation
        if 'DEPLOY_ID' in callback_context:
            req_payload['DeployId'] = callback_context['DEPLOY_ID']
        req = http.request(
            'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
        )
        payload = json.loads(req.data)
        deploy_status = payload['DeployStatus']
        if deploy_status in ('FAILED', 'FAULT', 'STOPPED', 'TIMED_OUT'):
            LOG.error(f"Workflow ${model.WorkflowName} creation failed with status ${deploy_status}")
            progress.status = OperationStatus.FAILED            
        elif deploy_status == 'IN_PROGRESS':
            model.InferenceApi = payload.get('ApiUri', 'MyTestUrl')
            LOG.info(f"Created workflow ${model.WorkflowName} successfully")
            progress.status = OperationStatus.SUCCESS
        else:            
            progress.status = OperationStatus.IN_PROGRESS
        return progress

    except TypeError as e:
        # exceptions module lets CloudFormation know the type of failure that occurred
        LOG.error(f"Workflow creation failed with status ${e}")
        raise exceptions.InternalFailure(f"was not expecting type {e}")
        # this can also be done by returning a failed progress event
        # return ProgressEvent.failed(HandlerErrorCode.InvalidRequest, f"was not expecting type {e}")
    return ProgressEvent(status=OperationStatus.SUCCESS, resourceModel=model, message="Workflow created")
```

**Comment by richardhboyd** [comment]
I just updated it to actually add the callback context variable.

**Comment by OElesin** [comment]
Thanks @richardhboyd. New error from logs:
```python
Exception caught
Traceback (most recent call last):
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 270, in __call__
    raise error
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 262, in __call__
    caller_sess, request, action, callback
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 121, in _invoke_handler
    is_in_progress = progress.status == OperationStatus.IN_PROGRESS
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by richardhboyd** [comment]
hmmm. That looks like the plugin is throwing the error?how are you invoking it?

**Comment by OElesin** [comment]
Invoking it via Cloudformation. Below is the entire `handlers.py`

```python
import json
import logging
from time import sleep
from typing import Any, MutableMapping, Optional
from urllib3 import PoolManager


from cloudformation_cli_python_lib import (
    Action,
    HandlerErrorCode,
    OperationStatus,
    ProgressEvent,
    Resource,
    SessionProxy,
    exceptions,
)


from .models import ResourceHandlerRequest, ResourceModel

# Use this logger to forward log messages to CloudWatch Logs.
LOG = logging.getLogger(__name__)
TYPE_NAME = "CD4AutoML::Workflow::Deploy"
CD4AUTO_ML_API = "https://someapi.com"
HTTP_REQUEST_HEADER = {"Accept": "application/json"}

resource = Resource(TYPE_NAME, ResourceModel)
test_entrypoint = resource.test_entrypoint
http = PoolManager()


@resource.handler(Action.CREATE)
def create_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
        callbackContext=callback_context if callback_context is not None else {}
    )
    try:
        req_payload = {
            'S3TrainingDataPath': model.S3TrainingDataPath,
            'TargetColumnName': model.TargetColumnName,
            'NotificationEmail': model.NotificationEmail,
            'WorkflowName': model.WorkflowName,
        }
        # auth = HTTPBasicAuth('API_KEY', '')
        LOG.info(f"Creating workflow ${model.WorkflowName}")
        # resuming from a long CREATE operation
        if 'DEPLOY_ID' in callback_context:
            req_payload['DeployId'] = callback_context['DEPLOY_ID']
        req = http.request(
            'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
        )

        payload = json.loads(req.data)
        deploy_status = payload['DeployStatus']
        progress.callbackContext['DEPLOY_ID'] = payload['DeployId']
        progress.callbackDelaySeconds = 20
        progress.status = OperationStatus.IN_PROGRESS
        if deploy_status in ('FAILED', 'FAULT', 'STOPPED', 'TIMED_OUT'):
            LOG.error(f"Workflow ${model.WorkflowName} creation failed with status ${deploy_status}")
            progress.status = OperationStatus.FAILED
        elif deploy_status == 'IN_PROGRESS':
            model.InferenceApi = payload.get('ApiUri', 'MyTestUrl')
            LOG.info(f"Created workflow ${model.WorkflowName} successfully")
            progress.status = OperationStatus.IN_PROGRESS
        else:
            progress.status = OperationStatus.SUCCESS
        return progress

    except TypeError as e:
        # exceptions module lets CloudFormation know the type of failure that occurred
        LOG.error(f"Workflow creation failed with status ${e}")
        raise exceptions.InternalFailure(f"was not expecting type {e}")
        # this can also be done by returning a failed progress event
        # return ProgressEvent.failed(HandlerErrorCode.InvalidRequest, f"was not expecting type {e}")
    return ProgressEvent(status=OperationStatus.SUCCESS, resourceModel=model, message="Workflow created")


@resource.handler(Action.CREATE)
def create_handler(
        session: Optional[SessionProxy],
        request: ResourceHandlerRequest,
        callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
    )


@resource.handler(Action.UPDATE)
def update_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
    )
    try:
        req_payload = {
            'S3TrainingDataPath': model.S3TrainingDataPath,
            'TargetColumnName': model.TargetColumnName,
            'NotificationEmail': model.NotificationEmail,
            'WorkflowName': model.WorkflowName,
        }
        # auth = HTTPBasicAuth('API_KEY', '')
        LOG.info(f"Updating workflow ${model.WorkflowName}")
        req = http.request(
            'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
        )
        payload = json.loads(req.data)
        deploy_status = payload['DeployStatus']
        while deploy_status == 'IN_PROGRESS':
            progress.status = OperationStatus.IN_PROGRESS
            req_payload['DeployId'] = payload['DeployId']
            req = http.request(
                'POST', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
            )
            payload = json.loads(req.data)
            deploy_status = payload['DeployStatus']
            sleep(30)
        if deploy_status in ('FAILED', 'FAULT', 'STOPPED', 'TIMED_OUT'):
            LOG.error(f"Workflow ${model.WorkflowName} update failed with status ${deploy_status}")
            raise exceptions.GeneralServiceException(f"update failed with status ${deploy_status}")
        else:
            # Setting Status to success will signal to cfn that the operation is complete
            model.InferenceApi = payload.get('ApiUri')
            LOG.info(f"Updated workflow ${model.WorkflowName} successfully")
            progress.status = OperationStatus.SUCCESS
    except TypeError as e:
        # exceptions module lets CloudFormation know the type of failure that occurred
        # raise exceptions.InternalFailure(f"was not expecting type {e}")
        # this can also be done by returning a failed progress event
        LOG.error(f"Workflow creation failed with status ${e}")
        return ProgressEvent.failed(HandlerErrorCode.InternalFailure, f"was not expecting type {e}")
    return ProgressEvent(status=OperationStatus.SUCCESS, resourceModel=model, message="Workflow updated")


@resource.handler(Action.DELETE)
def delete_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    progress: ProgressEvent = ProgressEvent(
        status=OperationStatus.IN_PROGRESS,
        resourceModel=model,
    )
    req_payload = {
        'S3TrainingDataPath': model.S3TrainingDataPath,
        'TargetColumnName': model.TargetColumnName,
        'NotificationEmail': model.NotificationEmail,
        'WorkflowName': model.WorkflowName,
    }
    http.request(
        'DELETE', url=CD4AUTO_ML_API, headers=HTTP_REQUEST_HEADER, body=json.dumps(req_payload)
    )
    return progress


@resource.handler(Action.READ)
def read_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    model = request.desiredResourceState
    # TODO: put code here
    return ProgressEvent(
        status=OperationStatus.SUCCESS,
        resourceModel=model,
    )


@resource.handler(Action.LIST)
def list_handler(
    session: Optional[SessionProxy],
    request: ResourceHandlerRequest,
    callback_context: MutableMapping[str, Any],
) -> ProgressEvent:
    # TODO: put code here
    return ProgressEvent(
        status=OperationStatus.SUCCESS,
        resourceModels=[],
    )

```

**Comment by richardhboyd** [comment]
can you try invoking it locally.

Create a file named test.json
````json
{
    "desiredResourceState": {
      "S3TrainingDataPath": "s3://data-bucket/churn/data.csv",
      "TargetColumnName": "Churn",
      "NotificationEmail": "test@example.com",
      "WorkflowName": "my-new-workflow",
      "Schedule": 14
    },
    "logicalResourceIdentifier": "MyChurnPredictionWorkflow"
}
````

Then run `sam local start-api` in one terminal (from the root of your resource) and `cfn invoke CREATE test.json` from another terminal (also at the root of the project)

**Comment by OElesin** [comment]
Throwing the same error
```python
Traceback (most recent call last):
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 156, in test_entrypoint
    return self._invoke_handler(session, request, action, callback_context)
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 121, in _invoke_handler
    is_in_progress = progress.status == OperationStatus.IN_PROGRESS
AttributeError: 'NoneType' object has no attribute 'status'
```

This was working before. I have reverted to initial code, and still the same error

**Comment by OElesin** [comment]
Seems I broke something. Everything works now. Thank you all. Closing this issue
